# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: demogroup

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- stage: demostage
  jobs:
  - job: username
    steps:
    - script: echo $(username)
  - job: password
    steps:
    - script: echo $(password)